NationalParksReservation/Models/Reservation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace NationalParksReservation.Models
{
    public class Reservation
    {
        [Required]
        public string ReservationName { get; set; }
        public int ReservationID { get; set; }
        public string CampgroundName { get; set; }
        public int SiteID { get; set; }
        public double DailyFee { get; set; }
        public DateTime ReservationStart { get; set; }
        public DateTime ReservationEnd { get; set; }
        public DateTime ReservationBooked { get; set; }

        public Reservation()
        {
        }

        public Reservation(int siteId, DateTime arrivalDate, DateTime depatureDate)
        {
            SiteID = siteId;
            ReservationStart = arrivalDate;
            ReservationEnd = depatureDate;
        }

        public Reservation(int siteId, DateTime arrivalDate, DateTime depatureDate, double cost)
        {
            SiteID = siteId;
            ReservationStart = arrivalDate;
            ReservationEnd = depatureDate;
            DailyFee = cost;
        }
    }
}

NationalParksReservation/Controllers/InterfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NationalParksReservation.Models;
using NationalParksReservation.DAL;

namespace NationalParksReservation.Controllers
{
    public class InterfaceController : Controller
    {
        private string connectionString = @"Data Source=localhost\sqlexpress;Initial Catalog=NationalPark;Integrated Security=True";
        
        // GET: Index
        public ActionResult Index()
        {
            ParkSqlDAL parkDAL = new ParkSqlDAL(connectionString);
            List<Park> parkList = parkDAL.GetAllParks();
            return View("Index", parkList);
        }
        //Get: ParkInterface
        public ActionResult ParkInterface(int id)
        {
            ParkSqlDAL parkDAL = new ParkSqlDAL(connectionString);
            Park park = parkDAL.GenerateParkName(id);
            return View("ParkInterface", park);
        }
    }
}

NationalParksReservation/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NationalParksReservation.Models;
using NationalParksReservation.DAL;

namespace NationalParksReservation.Controllers
{
    public class ReservationController : Controller
    {
        private string connectionString = @"Data Source=localhost\sqlexpress;Initial Catalog=NationalPark;Integrated Security=True";

        // GET: Index
        public ActionResult Index(CampSearch campSearch)
        {
            ReservationSqlDAL reservationDAL = new ReservationSqlDAL(connectionString);

            Session["CampSearch"] = campSearch;

            List<CampSite> siteList = reservationDAL.FindReservation(campSearch);

            return View("Index", siteList);
        }

        public ActionResult ParkScreen(ParkSearch parkSearch)
        {
            ReservationSqlDAL reservationDAL = new ReservationSqlDAL(connectionString);

            Session["ParkSearch"] = parkSearch;

            List<CampSite> siteList = reservationDAL.FindParkReservation(parkSearch);

            return View("ParkScreen", siteList);
        }

        public ActionResult ParkSubmit(int id)
        {
            //Session will always be filled but If/Else statement is there for testing purposes
            ParkSearch existingParkSearch = new ParkSearch();
            if (Session["ParkSearch"] != null)
            {
                existingParkSearch = Session["ParkSearch"] as ParkSearch;
            }
            else
            {
                existingParkSearch = new ParkSearch()
                {
                    ArrivalDate = DateTime.Today,
                    DepartureDate = DateTime.Today
                };
            }

            Reservation reservation = new Reservation(id, existingParkSearch.ArrivalDate, existingParkSearch.DepartureDate);

            return View("ParkSubmit", reservation);
        }

        [HttpPost]
        public ActionResult ParkSubmit(Reservation reservation)
        {
            return RedirectToAction("Confirmation", reservation);
        }

        // GET: Submit
        public ActionResult Submit(int id)
        {
            //Session will always be filled but If/Else statement is there for testing purposes
            CampSearch existingSearch = new CampSearch();
            if (Session["CampSearch"] != null)
            {
                existingSearch = Session["CampSearch"] as CampSearch;
            }
            else
            {
                existingSearch = new CampSearch()
                {
                    ArrivalDate = DateTime.Today,
                    DepartureDate = DateTime.Today,
                    DailyFee = 0.00
                };
            }

            Reservation reservation = new Reservation(id, existingSearch.ArrivalDate, existingSearch.DepartureDate, existingSearch.DailyFee);

            return View("Submit", reservation);
        }

        [HttpPost]
        public ActionResult Submit(Reservation reservation)
        {
            return RedirectToAction("Confirmation", reservation);
        }

        //GET: Confirmation
        public ActionResult Confirmation(Reservation reservation)
        {
            ReservationSqlDAL reservationDAL = new ReservationSqlDAL(connectionString);

            int reservationId = reservationDAL.CreateReservation(reservation.SiteID, reservation.ReservationStart, reservation.ReservationEnd, reservation.ReservationName);

            return View("Confirmation", reservationId);
        }
    }
} 

NationalParksReservation/Views/Reservation/Confirmation.cshtml
@model int
@{
    ViewBag.Title = "Confirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Congrats you reservation has been placed!</h2>
<p>Your reservation id is @Model</p>

NationalParksReservation/Views/Reservation/Index.cshtml
@using NationalParksReservation.Models;
@model List<CampSite>
@{
    ViewBag.Title = "Campsite Selection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model == null)
{
<p>You entered a date before today's date or a departure date before the arrival date.</p>
<p>Please go back and enter a valid date selection.</p>

<div id="selection">
    <ul>
        <li>@Html.ActionLink("Back to previous page", null, null, null, new { href = Request.UrlReferrer })</li>
    </ul>
</div>
}
else if (Model.Count == 0)
{
    <p>Sorry, there are no available campsites to display.</p>
    <p>Please check the date you entered, change your campsite requirements or choose another campground.</p>
    <br />

    <div id="selection">
        <ul>
            <li>@Html.ActionLink("Back to previous page", null, null, null, new { href = Request.UrlReferrer })</li>
        </ul>
    </div>
}
else
{
    <h3>Here are the results matching your criteria</h3>
    <div class="selection-container">
        <table>
            <tr>
                <td>Site No.</td>
                <td>Max Occup.</td>
                <td>Handicap Accessible</td>
                <td>Max RV Length</td>
                <td>Utility Hookups</td>
                <td>Daily Fee</td>
                <td>Reserve This Site?</td>
            </tr>
            @foreach (CampSite campSite in Model)
                {
                <tr>
                    <td>@campSite.SiteNumber</td>
                    <td>@campSite.MaxOccupancy</td>
                    <td>@campSite.Accessible</td>
                    @if (@campSite.MaxRvLength > 0)
                    {
                        <td>@campSite.MaxRvLength feet</td>
                    }
                    else
                    {
                        <td>N/A</td>
                    }
                    <td>@campSite.Utilities</td>
                    <td>@campSite.Cost.ToString("C")</td>
                    <td>@Html.ActionLink("Click Here!", "Submit", "Reservation", new { id = campSite.SiteId }, new { @class = "cs-selection" })</td>
                </tr>
            }
        </table>
    </div>
    <br />

    <div id="selection">
        <ul>
            <li>@Html.ActionLink("Return to Park Selection", "Index", "Interface")</li>
        </ul>
    </div>
}

NationalParksReservation/Views/Reservation/ParkScreen.cshtml
@using NationalParksReservation.Models;
@model List<CampSite>
@{
    ViewBag.Title = "Campsite Selection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model == null)
{
    <p>You entered a date before today's date or a departure date before the arrival date.</p>
    <p>Please go back and enter a valid date selection.</p>

    <div id="selection">
        <ul>
            <li>@Html.ActionLink("Back to previous page", null, null, null, new { href = Request.UrlReferrer })</li>
        </ul>
    </div>
}
else if (Model.Count == 0)
{
    <p>Sorry, there are no available campsites to display.</p>
    <p>Please check the date you entered, change your campsite requirements or choose another campground.</p>
    <br />

    <div id="selection">
        <ul>
            <li>@Html.ActionLink("Back to previous page", null, null, null, new { href = Request.UrlReferrer })</li>
        </ul>
    </div>
}
else
{
    <div class="selection-container">
        <table>
            <tr>
                <td>Campground</td>
                <td>Site No.</td>
                <td>Max Occup.</td>
                <td>Handicap Accessible</td>
                <td>Max RV Length</td>
                <td>Utility Hookups</td>
                <td>Daily Fee</td>
                <td>Reserve This Site?</td>
            </tr>
            @foreach (CampSite campSite in Model)
                {
                <tr>
                    <td>@campSite.Campground</td>
                    <td>@campSite.SiteNumber</td>
                    <td>@campSite.MaxOccupancy</td>
                    <td>@campSite.Accessible</td>
                    @if (@campSite.MaxRvLength > 0)
                    {
                        <td>@campSite.MaxRvLength feet</td>
                    }
                    else
                    {
                        <td>N/A</td>
                    }
                    <td>@campSite.Utilities</td>
                    <td>@campSite.Cost.ToString("C")</td>
                    <td>@Html.ActionLink("Click Here!", "ParkSubmit", "Reservation", new { id = campSite.SiteId }, new { @class = "cs-selection" })</td>
                </tr>
            }
        </table>
    </div>
    <br />

    <div id="selection">
        <ul>
            <li>@Html.ActionLink("Return to Park Selection", "Index", "Interface")</li>
        </ul>
    </div>
}

NationalParksReservation/Views/Reservation/ParkSubmit.cshtml
@using NationalParksReservation.Models;
@model Reservation

@{
    ViewBag.Title = "Submit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 id="confirmation-line">You Would Like To Reserve</h3>

@using (Html.BeginForm("ParkSubmit", "Reservation", FormMethod.Post))
{
    @Html.HiddenFor(m => m.SiteID)
    @Html.HiddenFor(m => m.ReservationStart)
    @Html.HiddenFor(m => m.ReservationEnd)

    <table class="selection-container">
        <tr>
            <td>Site ID</td>
            <td>Arrival Date</td>
            <td>Departure Date</td>
        </tr>

        <tr>
            <td>@Model.SiteID</td>
            <td>@Model.ReservationStart.ToShortDateString()</td>
            <td>@Model.ReservationEnd.ToShortDateString()</td>
        </tr>
    </table>

    <div class="input-form">
        @Html.Label("ReservationName", "What name would you like to make the reservation under?")
        @Html.EditorFor(m => m.ReservationName)
        @Html.ValidationMessageFor(m => m.ReservationName)
    </div>

    <br />
    <button>Make Reservation!</button>
}

NationalParksReservation/Views/Reservation/Submit.cshtml
@using NationalParksReservation.Models;
@model Reservation

@{
    ViewBag.Title = "Submit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 id="confirmation-line">You Would Like To Reserve</h3>

@using (Html.BeginForm("Submit", "Reservation", FormMethod.Post))
{
    @Html.HiddenFor(m => m.SiteID)
    @Html.HiddenFor(m => m.ReservationStart)
    @Html.HiddenFor(m => m.ReservationEnd)
    @Html.HiddenFor(m => m.DailyFee)

    <table class="selection-container">
        <tr>
            <td>Site ID</td>
            <td>Arrival Date</td>
            <td>Departure Date</td>
            <td>Cost</td>
        </tr>

        <tr>
            <td>@Model.SiteID</td>
            <td>@Model.ReservationStart.ToShortDateString()</td>
            <td>@Model.ReservationEnd.ToShortDateString()</td>
            <td>@Model.DailyFee.ToString("C")</td>
        </tr>
    </table>

    <div class="input-form">
        <br />
        @Html.Label("ReservationName", "What name would you like to make the reservation under?")
        @Html.EditorFor(m => m.ReservationName)
        @Html.ValidationMessageFor(m => m.ReservationName)
    </div>

    <br />
    <button>Make Reservation!</button>
}