NationalParksReservation/Models/Campground.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace NationalParksReservation.Models
{
    public class Campground
    {
        public int CampgroundId { get; set; }
        public string ParkName { get; set; }
        public string CampgroundName { get; set; }
        public string OpenMonth { get; set; }
        public string CloseMonth { get; set; }
        public double DailyFee { get; set; }

        public string ToMonth(int month)
        {
            if (month == 1)
            {
                return "January";
            }
            else if (month == 2)
            {
                return "February";
            }
            else if (month == 3)
            {
                return "March";
            }
            else if (month == 4)
            {
                return "April";
            }
            else if (month == 5)
            {
                return "May";
            }
            else if (month == 6)
            {
                return "June";
            }
            else if (month == 7)
            {
                return "July";
            }
            else if (month == 8)
            {
                return "August";
            }
            else if (month == 9)
            {
                return "September";
            }
            else if (month == 10)
            {
                return "October";
            }
            else if (month == 11)
            {
                return "November";
            }
            else if (month == 12)
            {
                return "December";
            }
            return null;
        }
    }
}

NationalParksReservation/Models/ParkSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace NationalParksReservation.Models
{
    public class ParkSearch
    {
        [Required]
        [DataType(DataType.Date)]
        public DateTime ArrivalDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime DepartureDate { get; set; }

        [Required]
        public int MaxOccupancy { get; set; }

        public int ParkId { get; set; }
        public int SiteId { get; set; }
        public string ParkName { get; set; }
        public bool IsAccessible { get; set; }
        public int RVLength { get; set; }
        public bool NeedUtilities { get; set; }
    }
}

NationalParksReservation/Controllers/CampgroundController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NationalParksReservation.Models;
using NationalParksReservation.DAL;

namespace NationalParksReservation.Controllers
{
    public class CampgroundController : Controller
    {
        private string connectionString = @"Data Source=localhost\sqlexpress;Initial Catalog=NationalPark;Integrated Security=True";

        // GET: Campground
        public ActionResult Index(int id)
        {
            CampgroundSqlDAL campgroundDAL = new CampgroundSqlDAL(connectionString);
            List<Campground> campgroundList = campgroundDAL.ListCampgrounds(id);

            return View("Index", campgroundList);
        }

        //GET: ParkSearch
        public ActionResult ParkSearch(int id)
        {
            ParkSearchSqlDAL parkSearchDAL = new ParkSearchSqlDAL(connectionString);
            ParkSearch parkSearch = parkSearchDAL.RetrieveInfo(id);

            return View("ParkSearch", parkSearch);
        }

        [HttpPost]
        public ActionResult ParkSearch(ParkSearch parkSearch)
        {
            return RedirectToAction("ParkScreen", "Reservation", parkSearch);
        }

        //GET: Search
        public ActionResult Search(int id)
        {
            CampSiteSqlDAL campSiteDAL = new CampSiteSqlDAL(connectionString);
            CampSearch campSearch = campSiteDAL.RetrieveInfo(id);

            return View("Search", campSearch);
        }

        [HttpPost]
        public ActionResult Search(CampSearch campSearch)
        {
            return RedirectToAction("Index", "Reservation", campSearch);
        }
    }
}

NationalParksReservation/Controllers/InterfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NationalParksReservation.Models;
using NationalParksReservation.DAL;

namespace NationalParksReservation.Controllers
{
    public class InterfaceController : Controller
    {
        private string connectionString = @"Data Source=localhost\sqlexpress;Initial Catalog=NationalPark;Integrated Security=True";
        
        // GET: Index
        public ActionResult Index()
        {
            ParkSqlDAL parkDAL = new ParkSqlDAL(connectionString);
            List<Park> parkList = parkDAL.GetAllParks();
            return View("Index", parkList);
        }
        //Get: ParkInterface
        public ActionResult ParkInterface(int id)
        {
            ParkSqlDAL parkDAL = new ParkSqlDAL(connectionString);
            Park park = parkDAL.GenerateParkName(id);
            return View("ParkInterface", park);
        }
    }
}

NationalParksReservation/Views/Campground/Index.cshtml
@using NationalParksReservation.Models;
@model List<Campground>

@{ int counter = 1; }

@{
    ViewBag.Title = "Campground Information";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Click Campground Name To Search Available Campsites</h3>

<div id="table-container">
    <table>
        <tr>
            <td> </td>
            <th>Name</th>
            <th>Open</th>
            <th>Close</th>
            <th>Daily Fee</th>
        </tr>
        @foreach (Campground campground in Model)
        {
            <tr>
                <td>#@counter</td>
                <td>@Html.ActionLink(@campground.CampgroundName, "Search", "Campground", new { id = campground.CampgroundId }, new { @class = "cg-selection" })</td>
                <td>@campground.OpenMonth</td>
                <td>@campground.CloseMonth</td>
                <td>@campground.DailyFee.ToString("C")</td>
            </tr>

            counter++;
        }
    </table>
</div>
<br />

<div id="selection">
    <ul>
        <li>@Html.ActionLink("Return to Park Selection", "Index", "Interface")</li>
    </ul>
</div>

NationalParksReservation/Views/Campground/ParkSearch.cshtml
@using NationalParksReservation.Models;
@model ParkSearch
@{
    ViewBag.Title = "Search Park";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("ParkSearch", "Campground", FormMethod.Post))
{
    <h3>Search Criteria for @Model.ParkName National Park</h3>
    <br />

    @Html.HiddenFor(m => m.ParkId)

    <div class="input-form">
        @Html.Label("ArrivalDate", "What is your date of arrival?")
        @Html.EditorFor(m => m.ArrivalDate)
        @Html.ValidationMessageFor(m => m.ArrivalDate)
    </div>

    <div class="input-form">
        @Html.Label("DepartureDate", "What is your date of departure?")
        @Html.EditorFor(m => m.DepartureDate)
        @Html.ValidationMessageFor(m => m.DepartureDate)
    </div>

    <div class="input-form">
        @Html.Label("MaxOccupancy", "(Required) Enter the minimum amount of people that will be attending")
        @Html.TextBoxFor(m => m.MaxOccupancy)
        @Html.ValidationMessageFor(m => m.MaxOccupancy)
    </div>

    <div class="input-form">
        @Html.Label("IsAccessible", "Do you need a handicap accessible site?")
        @Html.CheckBoxFor(m => m.IsAccessible)
    </div>

    <div class="input-form">
        @Html.Label("RVLength", "What is the size of your RV in feet? (If you do not have an RV then please enter 0)")
        @Html.TextBoxFor(m => m.RVLength)
    </div>

    <div class="input-form">
        @Html.Label("NeedUtilities", "Do you need a hookup for utilities?")
        @Html.CheckBoxFor(m => m.NeedUtilities)
    </div>
    <button>Search!</button>

    <div id="selection">
        <br />
        <ul>
            <li>@Html.ActionLink("Back to previous page", "Index", "Campground", new { id = Model.ParkId }, null)</li>
        </ul>
    </div>
}

NationalParksReservation/Views/Campground/Search.cshtml
@using NationalParksReservation.Models;
@model CampSearch
@{
    ViewBag.Title = "Search Campground";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search</h2>
@using (Html.BeginForm("Search", "Campground", FormMethod.Post))
{
    <div id="table-container">
        <table>
            <tr>
                <td>Name</td>
                <td>Open</td>
                <td>Close</td>
                <td>Daily Fee</td>
            </tr>
            <tr>
                <td>@Model.CampgroundName</td>
                <td>@Model.OpenMonth</td>
                <td>@Model.CloseMonth</td>
                <td>@Model.DailyFee.ToString("C")</td>
            </tr>
        </table>
    </div>
    <br />

    @Html.HiddenFor(m => m.CampgroundId)
    @Html.HiddenFor(m => m.DailyFee)

    <div class="input-form">
        @Html.Label("ArrivalDate", "What is your date of arrival?")
        @Html.EditorFor(m => m.ArrivalDate)
        @Html.ValidationMessageFor(m => m.ArrivalDate)
    </div>

    <div class="input-form">
        @Html.Label("DepartureDate", "What is your date of departure?")
        @Html.EditorFor(m => m.DepartureDate)
        @Html.ValidationMessageFor(m => m.DepartureDate)
    </div>

    <div class="input-form">
        @Html.Label("MaxOccupancy", "(Required) Enter the minimum amount of people that will be attending")
        @Html.TextBoxFor(m => m.MaxOccupancy)
        @Html.ValidationMessageFor(m => m.MaxOccupancy)
    </div>

    <div class="input-form">
        @Html.Label("IsAccessible", "Do you need a handicap accessible site?")
        @Html.CheckBoxFor(m => m.IsAccessible)
    </div>

    <div class="input-form">
        @Html.Label("RVLength", "What is the size of your RV in feet? (If you do not have an RV then please enter 0)")
        @Html.TextBoxFor(m => m.RVLength)
    </div>

    <div class="input-form">
        @Html.Label("NeedUtilities", "Do you need a hookup for utilities?")
        @Html.CheckBoxFor(m => m.NeedUtilities)
    </div>
    <button>Search!</button>

    <div id="selection">
        <br />
        <ul>
            <li>@Html.ActionLink("Back to previous page", "Index", "Campground", new { id = Model.CampgroundId }, null)</li>
        </ul>
    </div>
}